# Generated by Django 4.1.6 on 2023-02-09 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('birthdate', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id_name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='id_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('user_type', models.IntegerField(blank=True, choices=[(0, 'teacher'), (1, 'student')], null=True)),
                ('ss_name', models.CharField(blank=True, default='none', max_length=10, null=True)),
                ('ss_age', models.DateField(blank=True, null=True)),
                ('offer_box', models.TextField(blank=True, default='none', null=True)),
                ('class_number', models.IntegerField(default=0, null=True)),
                ('my_teacher', models.CharField(blank=True, default='none', max_length=40, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
