# Generated by Django 4.1.6 on 2023-02-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0002_readyroom_remove_profile_ss_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='readyroom',
            old_name='ready',
            new_name='readyName',
        ),
        migrations.AddField(
            model_name='readyroom',
            name='readyState',
            field=models.BooleanField(default=False),
        ),
    ]
