# Generated by Django 4.1.6 on 2023-02-17 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0003_rename_ready_readyroom_readyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='ss_name',
            field=models.CharField(blank=True, default='none', max_length=10, null=True),
        ),
    ]
